// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "follows", uniqueConstraints = {@UniqueConstraint(columnNames = {"follower_id", "following_id"})})
public class Follow {
    @Id
    @SequenceGenerator(name = "follow_seq", sequenceName = "FOLLOW_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "follow_seq")
    @Column(name = "FOLLOW_ID")
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "follower_id", nullable = false)
    private User follower;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "following_id", nullable = false)
    private User following;
    @CreationTimestamp
    private LocalDateTime createdAt;
    public static class FollowBuilder {
        private Long id;
        private User follower;
        private User following;
        private LocalDateTime createdAt;
        FollowBuilder() {
        }

        /**
         * @return {@code this}.
         */
        public Follow.FollowBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Follow.FollowBuilder follower(final User follower) {
            this.follower = follower;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Follow.FollowBuilder following(final User following) {
            this.following = following;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Follow.FollowBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }
        public Follow build() {
            return new Follow(this.id, this.follower, this.following, this.createdAt);
        }

        @java.lang.Override
        public java.lang.String toString() {
            return "Follow.FollowBuilder(id=" + this.id + ", follower=" + this.follower + ", following=" + this.following + ", createdAt=" + this.createdAt + ")";
        }
    }
    public static Follow.FollowBuilder builder() {
        return new Follow.FollowBuilder();
    }
    public Long getId() {
        return this.id;
    }
    public User getFollower() {
        return this.follower;
    }
    public User getFollowing() {
        return this.following;
    }
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
    public void setId(final Long id) {
        this.id = id;
    }
    public void setFollower(final User follower) {
        this.follower = follower;
    }
    public void setFollowing(final User following) {
        this.following = following;
    }
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Follow)) return false;
        final Follow other = (Follow) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$follower = this.getFollower();
        final java.lang.Object other$follower = other.getFollower();
        if (this$follower == null ? other$follower != null : !this$follower.equals(other$follower)) return false;
        final java.lang.Object this$following = this.getFollowing();
        final java.lang.Object other$following = other.getFollowing();
        if (this$following == null ? other$following != null : !this$following.equals(other$following)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Follow;
    }

    @java.lang.Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $follower = this.getFollower();
        result = result * PRIME + ($follower == null ? 43 : $follower.hashCode());
        final java.lang.Object $following = this.getFollowing();
        result = result * PRIME + ($following == null ? 43 : $following.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    public java.lang.String toString() {
        return "Follow(id=" + this.getId() + ", follower=" + this.getFollower() + ", following=" + this.getFollowing() + ", createdAt=" + this.getCreatedAt() + ")";
    }
    public Follow() {
    }
    public Follow(final Long id, final User follower, final User following, final LocalDateTime createdAt) {
        this.id = id;
        this.follower = follower;
        this.following = following;
        this.createdAt = createdAt;
    }
}
