// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "post_likes", uniqueConstraints = {@UniqueConstraint(columnNames = {"post_id", "user_id"})})
public class Like {
    @Id
    @SequenceGenerator(name = "like_seq", sequenceName = "LIKE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "like_seq")
    @Column(name = "LIKE_ID")
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_id", nullable = false)
    private Post post;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @CreationTimestamp
    private LocalDateTime createdAt;
    public static class LikeBuilder {
        private Long id;
        private Post post;
        private User user;
        private LocalDateTime createdAt;
        LikeBuilder() {
        }

        /**
         * @return {@code this}.
         */
        public Like.LikeBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Like.LikeBuilder post(final Post post) {
            this.post = post;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Like.LikeBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Like.LikeBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }
        public Like build() {
            return new Like(this.id, this.post, this.user, this.createdAt);
        }

        @java.lang.Override
        public java.lang.String toString() {
            return "Like.LikeBuilder(id=" + this.id + ", post=" + this.post + ", user=" + this.user + ", createdAt=" + this.createdAt + ")";
        }
    }
    public static Like.LikeBuilder builder() {
        return new Like.LikeBuilder();
    }
    public Long getId() {
        return this.id;
    }
    public Post getPost() {
        return this.post;
    }
    public User getUser() {
        return this.user;
    }
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
    public void setId(final Long id) {
        this.id = id;
    }
    public void setPost(final Post post) {
        this.post = post;
    }
    public void setUser(final User user) {
        this.user = user;
    }
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Like)) return false;
        final Like other = (Like) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$post = this.getPost();
        final java.lang.Object other$post = other.getPost();
        if (this$post == null ? other$post != null : !this$post.equals(other$post)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Like;
    }

    @java.lang.Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $post = this.getPost();
        result = result * PRIME + ($post == null ? 43 : $post.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    public java.lang.String toString() {
        return "Like(id=" + this.getId() + ", post=" + this.getPost() + ", user=" + this.getUser() + ", createdAt=" + this.getCreatedAt() + ")";
    }
    public Like() {
    }
    public Like(final Long id, final Post post, final User user, final LocalDateTime createdAt) {
        this.id = id;
        this.post = post;
        this.user = user;
        this.createdAt = createdAt;
    }
}
