// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "messages")
public class Message {
    @Id
    @SequenceGenerator(name = "message_seq", sequenceName = "MESSAGE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "message_seq")
    @Column(name = "MESSAGE_ID")
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "receiver_id", nullable = false)
    private User receiver;
    @Column(nullable = false, length = 2000)
    private String content;
    @CreationTimestamp
    private LocalDateTime sentAt;
    @Column(nullable = false)
    private boolean isRead;
    public static class MessageBuilder {
        private Long id;
        private User sender;
        private User receiver;
        private String content;
        private LocalDateTime sentAt;
        private boolean isRead;
        MessageBuilder() {
        }

        /**
         * @return {@code this}.
         */
        public Message.MessageBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Message.MessageBuilder sender(final User sender) {
            this.sender = sender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Message.MessageBuilder receiver(final User receiver) {
            this.receiver = receiver;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Message.MessageBuilder content(final String content) {
            this.content = content;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Message.MessageBuilder sentAt(final LocalDateTime sentAt) {
            this.sentAt = sentAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Message.MessageBuilder isRead(final boolean isRead) {
            this.isRead = isRead;
            return this;
        }
        public Message build() {
            return new Message(this.id, this.sender, this.receiver, this.content, this.sentAt, this.isRead);
        }

        @java.lang.Override
        public java.lang.String toString() {
            return "Message.MessageBuilder(id=" + this.id + ", sender=" + this.sender + ", receiver=" + this.receiver + ", content=" + this.content + ", sentAt=" + this.sentAt + ", isRead=" + this.isRead + ")";
        }
    }
    public static Message.MessageBuilder builder() {
        return new Message.MessageBuilder();
    }
    public Long getId() {
        return this.id;
    }
    public User getSender() {
        return this.sender;
    }
    public User getReceiver() {
        return this.receiver;
    }
    public String getContent() {
        return this.content;
    }
    public LocalDateTime getSentAt() {
        return this.sentAt;
    }
    public boolean isRead() {
        return this.isRead;
    }
    public void setId(final Long id) {
        this.id = id;
    }
    public void setSender(final User sender) {
        this.sender = sender;
    }
    public void setReceiver(final User receiver) {
        this.receiver = receiver;
    }
    public void setContent(final String content) {
        this.content = content;
    }
    public void setSentAt(final LocalDateTime sentAt) {
        this.sentAt = sentAt;
    }
    public void setRead(final boolean isRead) {
        this.isRead = isRead;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Message)) return false;
        final Message other = (Message) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isRead() != other.isRead()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$sender = this.getSender();
        final java.lang.Object other$sender = other.getSender();
        if (this$sender == null ? other$sender != null : !this$sender.equals(other$sender)) return false;
        final java.lang.Object this$receiver = this.getReceiver();
        final java.lang.Object other$receiver = other.getReceiver();
        if (this$receiver == null ? other$receiver != null : !this$receiver.equals(other$receiver)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        final java.lang.Object this$sentAt = this.getSentAt();
        final java.lang.Object other$sentAt = other.getSentAt();
        if (this$sentAt == null ? other$sentAt != null : !this$sentAt.equals(other$sentAt)) return false;
        return true;
    }
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Message;
    }

    @java.lang.Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isRead() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $sender = this.getSender();
        result = result * PRIME + ($sender == null ? 43 : $sender.hashCode());
        final java.lang.Object $receiver = this.getReceiver();
        result = result * PRIME + ($receiver == null ? 43 : $receiver.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $sentAt = this.getSentAt();
        result = result * PRIME + ($sentAt == null ? 43 : $sentAt.hashCode());
        return result;
    }

    @java.lang.Override
    public java.lang.String toString() {
        return "Message(id=" + this.getId() + ", sender=" + this.getSender() + ", receiver=" + this.getReceiver() + ", content=" + this.getContent() + ", sentAt=" + this.getSentAt() + ", isRead=" + this.isRead() + ")";
    }
    public Message() {
    }
    public Message(final Long id, final User sender, final User receiver, final String content, final LocalDateTime sentAt, final boolean isRead) {
        this.id = id;
        this.sender = sender;
        this.receiver = receiver;
        this.content = content;
        this.sentAt = sentAt;
        this.isRead = isRead;
    }
}
