// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "saved_posts")
public class SavedPost {
    @Id
    @SequenceGenerator(name = "saved_post_seq", sequenceName = "SAVED_POST_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "saved_post_seq")
    @Column(name = "SAVED_POST_ID")
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user; // The user who bookmarked it
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_id", nullable = false)
    private Post post; // The bookmarked post
    @CreationTimestamp
    private LocalDateTime savedAt;
    public static class SavedPostBuilder {
        private Long id;
        private User user;
        private Post post;
        private LocalDateTime savedAt;
        SavedPostBuilder() {
        }

        /**
         * @return {@code this}.
         */
        public SavedPost.SavedPostBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public SavedPost.SavedPostBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public SavedPost.SavedPostBuilder post(final Post post) {
            this.post = post;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public SavedPost.SavedPostBuilder savedAt(final LocalDateTime savedAt) {
            this.savedAt = savedAt;
            return this;
        }
        public SavedPost build() {
            return new SavedPost(this.id, this.user, this.post, this.savedAt);
        }

        @java.lang.Override
        public java.lang.String toString() {
            return "SavedPost.SavedPostBuilder(id=" + this.id + ", user=" + this.user + ", post=" + this.post + ", savedAt=" + this.savedAt + ")";
        }
    }
    public static SavedPost.SavedPostBuilder builder() {
        return new SavedPost.SavedPostBuilder();
    }
    public Long getId() {
        return this.id;
    }
    public User getUser() {
        return this.user;
    }
    public Post getPost() {
        return this.post;
    }
    public LocalDateTime getSavedAt() {
        return this.savedAt;
    }
    public void setId(final Long id) {
        this.id = id;
    }
    public void setUser(final User user) {
        this.user = user;
    }
    public void setPost(final Post post) {
        this.post = post;
    }
    public void setSavedAt(final LocalDateTime savedAt) {
        this.savedAt = savedAt;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SavedPost)) return false;
        final SavedPost other = (SavedPost) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$post = this.getPost();
        final java.lang.Object other$post = other.getPost();
        if (this$post == null ? other$post != null : !this$post.equals(other$post)) return false;
        final java.lang.Object this$savedAt = this.getSavedAt();
        final java.lang.Object other$savedAt = other.getSavedAt();
        if (this$savedAt == null ? other$savedAt != null : !this$savedAt.equals(other$savedAt)) return false;
        return true;
    }
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SavedPost;
    }

    @java.lang.Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $post = this.getPost();
        result = result * PRIME + ($post == null ? 43 : $post.hashCode());
        final java.lang.Object $savedAt = this.getSavedAt();
        result = result * PRIME + ($savedAt == null ? 43 : $savedAt.hashCode());
        return result;
    }

    @java.lang.Override
    public java.lang.String toString() {
        return "SavedPost(id=" + this.getId() + ", user=" + this.getUser() + ", post=" + this.getPost() + ", savedAt=" + this.getSavedAt() + ")";
    }
    public SavedPost() {
    }
    public SavedPost(final Long id, final User user, final Post post, final LocalDateTime savedAt) {
        this.id = id;
        this.user = user;
        this.post = post;
        this.savedAt = savedAt;
    }
}
