spring.application.name=revconnect
server.port=8081
spring.datasource.url=jdbc:oracle:thin:@db.freesql.com:1521/23ai_34ui2
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=GOWTHAMREDDY20201_SCHEMA_AG8XG
spring.datasource.password=YH4UVL08413WGI80o2W7QWJIQ$YF9K
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
