// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.controller;

import com.revconnect.app.service.PostService;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class ExploreController {
    private final PostService postService;

    @GetMapping("/explore")
    public String getExplorePage(Model model, @AuthenticationPrincipal UserDetails userDetails) {
        if (userDetails != null) {
            model.addAttribute("posts", postService.getExploreFeed(userDetails.getUsername()));
        } else {
            model.addAttribute("posts", postService.getAllPosts());
        }
        model.addAttribute("trendingHashtags", postService.getTrendingHashtags());
        return "explore";
    }

    @GetMapping("/explore/hashtag")
    public String searchByHashtag(@org.springframework.web.bind.annotation.RequestParam String tag, Model model) {
        model.addAttribute("posts", postService.searchByHashtag(tag));
        model.addAttribute("searchTag", tag);
        model.addAttribute("trendingHashtags", postService.getTrendingHashtags());
        return "explore";
    }

    public ExploreController(final PostService postService) {
        this.postService = postService;
    }
}
