// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.controller;

import com.revconnect.app.service.InteractionService;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/interactions")
public class InteractionController {
    private final InteractionService interactionService;

    @PostMapping("/post/{id}/like")
    public String toggleLike(@PathVariable Long id, @AuthenticationPrincipal UserDetails userDetails) {
        interactionService.toggleLike(id, userDetails.getUsername());
        return "redirect:/posts/" + id;
    }

    @PostMapping("/post/{id}/comment")
    public String addComment(@PathVariable Long id, @RequestParam String content,
            @AuthenticationPrincipal UserDetails userDetails) {
        interactionService.addComment(id, userDetails.getUsername(), content);
        return "redirect:/posts/" + id;
    }

    @PostMapping("/comment/{id}/delete")
    public String deleteComment(@PathVariable Long id, @AuthenticationPrincipal UserDetails userDetails,
            @RequestParam(required = false) Long postId) {
        interactionService.deleteComment(id, userDetails.getUsername());
        return postId != null ? "redirect:/posts/" + postId : "redirect:/";
    }

    @PostMapping("/post/{id}/share")
    public String sharePost(@PathVariable Long id, @AuthenticationPrincipal UserDetails userDetails) {
        interactionService.sharePost(id, userDetails.getUsername());
        return "redirect:/";
    }

    @PostMapping("/post/{id}/view")
    @ResponseBody
    public org.springframework.http.ResponseEntity<Void> trackView(@PathVariable Long id,
            @AuthenticationPrincipal UserDetails userDetails) {
        if (userDetails != null) {
            interactionService.trackView(id, userDetails.getUsername());
        }
        return org.springframework.http.ResponseEntity.ok().build();
    }

    public InteractionController(final InteractionService interactionService) {
        this.interactionService = interactionService;
    }
}
