// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.controller;

import com.revconnect.app.entity.Message;
import com.revconnect.app.entity.User;
import com.revconnect.app.service.MessageService;
import com.revconnect.app.service.UserService;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@Controller
@RequestMapping("/messages")
public class MessageController {
    private final MessageService messageService;
    private final UserService userService;

    @GetMapping
    public String getInbox(Model model, @AuthenticationPrincipal UserDetails userDetails) {
        if (userDetails == null) {
            return "redirect:/login";
        }
        List<User> chatPartners = messageService.getChatPartners(userDetails.getUsername());
        model.addAttribute("chatPartners", chatPartners);
        model.addAttribute("currentUser", userService.findByUsername(userDetails.getUsername()));
        return "messages";
    }

    @GetMapping("/{partnerUsername}")
    public String getConversation(@PathVariable String partnerUsername, Model model, @AuthenticationPrincipal UserDetails userDetails) {
        List<User> chatPartners = messageService.getChatPartners(userDetails.getUsername());
        List<Message> conversation = messageService.getConversation(userDetails.getUsername(), partnerUsername);
        // Mark fetched messages from the partner as read
        for (Message m : conversation) {
            if (m.getSender().getUsername().equals(partnerUsername) && !m.isRead()) {
                messageService.markAsRead(m.getId(), userDetails.getUsername());
            }
        }
        model.addAttribute("chatPartners", chatPartners);
        model.addAttribute("conversation", conversation);
        model.addAttribute("partnerUsername", partnerUsername);
        model.addAttribute("currentUser", userService.findByUsername(userDetails.getUsername()));
        return "messages";
    }

    @PostMapping("/{receiverUsername}")
    public String sendMessage(@PathVariable String receiverUsername, @RequestParam String content, @AuthenticationPrincipal UserDetails userDetails) {
        messageService.sendMessage(userDetails.getUsername(), receiverUsername, content);
        return "redirect:/messages/" + receiverUsername;
    }
    public MessageController(final MessageService messageService, final UserService userService) {
        this.messageService = messageService;
        this.userService = userService;
    }
}
