// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.controller;

import com.revconnect.app.service.NetworkService;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/network")
public class NetworkController {
    private final NetworkService networkService;

    @PostMapping("/follow/{username}")
    public String followUser(@PathVariable String username, @AuthenticationPrincipal UserDetails userDetails,
            @RequestHeader(value = "Referer", required = false) String referer) {
        networkService.followUser(userDetails.getUsername(), username);
        if (referer != null && !referer.isEmpty()) {
            return "redirect:" + referer;
        }
        return "redirect:/users/profile/" + username;
    }

    @PostMapping("/unfollow/{username}")
    public String unfollowUser(@PathVariable String username, @AuthenticationPrincipal UserDetails userDetails,
            @RequestHeader(value = "Referer", required = false) String referer) {
        networkService.unfollowUser(userDetails.getUsername(), username);
        if (referer != null && !referer.isEmpty()) {
            return "redirect:" + referer;
        }
        return "redirect:/users/profile/" + username;
    }

    @PostMapping("/request/{username}")
    public String sendConnectionRequest(@PathVariable String username, @AuthenticationPrincipal UserDetails userDetails,
            @RequestHeader(value = "Referer", required = false) String referer) {
        networkService.sendConnectionRequest(userDetails.getUsername(), username);
        if (referer != null && !referer.isEmpty()) {
            return "redirect:" + referer;
        }
        return "redirect:/users/profile/" + username;
    }

    @PostMapping("/accept/{username}")
    public String acceptConnection(@PathVariable String username, @AuthenticationPrincipal UserDetails userDetails,
            @RequestHeader(value = "Referer", required = false) String referer) {
        networkService.acceptConnection(userDetails.getUsername(), username);
        if (referer != null && !referer.isEmpty()) {
            return "redirect:" + referer;
        }
        return "redirect:/network/followers";
    }

    @PostMapping("/reject/{username}")
    public String rejectConnection(@PathVariable String username, @AuthenticationPrincipal UserDetails userDetails,
            @RequestHeader(value = "Referer", required = false) String referer) {
        networkService.rejectConnection(userDetails.getUsername(), username);
        if (referer != null && !referer.isEmpty()) {
            return "redirect:" + referer;
        }
        return "redirect:/network/followers";
    }

    @GetMapping("/followers")
    public String viewFollowers(Model model, @AuthenticationPrincipal UserDetails userDetails) {
        model.addAttribute("followers", networkService.getFollowers(userDetails.getUsername()));
        model.addAttribute("pendingRequests", networkService.getPendingRequests(userDetails.getUsername()));
        model.addAttribute("title", "My Followers");
        return "network/followers";
    }

    @GetMapping("/following")
    public String viewFollowing(Model model, @AuthenticationPrincipal UserDetails userDetails) {
        model.addAttribute("following", networkService.getFollowing(userDetails.getUsername()));
        model.addAttribute("pendingRequests", networkService.getPendingRequests(userDetails.getUsername()));
        model.addAttribute("title", "Users I Follow");
        return "network/following";
    }

    @GetMapping("/requests")
    public String viewPendingRequests(Model model, @AuthenticationPrincipal UserDetails userDetails) {
        model.addAttribute("pendingRequests", networkService.getPendingRequests(userDetails.getUsername()));
        model.addAttribute("title", "Pending Connection Requests");
        return "network/requests";
    }

    public NetworkController(final NetworkService networkService) {
        this.networkService = networkService;
    }
}
