// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.controller;

import com.revconnect.app.service.PostService;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PathVariable;

@Controller
@RequestMapping("/posts")
public class PostController {
    private final PostService postService;
    private final com.revconnect.app.service.InteractionService interactionService;

    @PostMapping("/create")
    public String createPost(@AuthenticationPrincipal UserDetails userDetails,
            @RequestParam String content,
            @RequestParam(required = false) String hashtags,
            @RequestParam(value = "image", required = false) MultipartFile image,
            @RequestParam(required = false) String ctaLabel,
            @RequestParam(required = false) String ctaLink,
            @RequestParam(required = false) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE_TIME) java.time.LocalDateTime scheduledFor,
            @RequestParam(required = false, defaultValue = "false") boolean isPinned,
            @RequestParam(required = false, defaultValue = "false") boolean isPromotional) {
        postService.createPost(userDetails.getUsername(), content, hashtags, image, ctaLabel, ctaLink, scheduledFor,
                isPinned, isPromotional);
        return "redirect:/";
    }

    @PostMapping("/{id}/edit")
    public String editPost(@PathVariable Long id, @AuthenticationPrincipal UserDetails userDetails,
            @RequestParam String content, @RequestParam(required = false) String hashtags,
            @RequestParam(required = false) String ctaLabel,
            @RequestParam(required = false) String ctaLink,
            @RequestParam(required = false) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE_TIME) java.time.LocalDateTime scheduledFor,
            @RequestParam(required = false, defaultValue = "false") boolean isPinned,
            @RequestParam(required = false, defaultValue = "false") boolean isPromotional) {
        postService.updatePost(id, userDetails.getUsername(), content, hashtags, ctaLabel, ctaLink, scheduledFor,
                isPinned, isPromotional);
        return "redirect:/posts/" + id;
    }

    @PostMapping("/{id}/delete")
    public String deletePost(@PathVariable Long id, @AuthenticationPrincipal UserDetails userDetails) {
        postService.deletePost(id, userDetails.getUsername());
        return "redirect:/users";
    }

    @PostMapping("/{id}/pin")
    public String togglePinPost(@PathVariable Long id, @AuthenticationPrincipal UserDetails userDetails) {
        postService.togglePin(id, userDetails.getUsername());
        return "redirect:/users";
    }

    @org.springframework.web.bind.annotation.GetMapping("/{id}")
    public String viewPost(@org.springframework.web.bind.annotation.PathVariable Long id,
            org.springframework.ui.Model model,
            @org.springframework.security.core.annotation.AuthenticationPrincipal org.springframework.security.core.userdetails.UserDetails userDetails) {
        model.addAttribute("post", postService.getPostById(id));
        model.addAttribute("comments", interactionService.getCommentsForPost(id));
        if (userDetails != null) {
            model.addAttribute("currentUsername", userDetails.getUsername());
        } else {
            model.addAttribute("currentUsername", null);
        }
        return "post";
    }

    public PostController(final PostService postService,
            final com.revconnect.app.service.InteractionService interactionService) {
        this.postService = postService;
        this.interactionService = interactionService;
    }
}
