// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.controller;

import com.revconnect.app.entity.User;
import com.revconnect.app.service.PostService;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import com.revconnect.app.entity.*;
import com.revconnect.app.repository.*;
import com.revconnect.app.service.FileStorageService;
import com.revconnect.app.service.NetworkService;
import org.springframework.web.multipart.MultipartFile;
import java.math.BigDecimal;

@Controller
@RequestMapping("/users")
public class ProfileController {
    private final UserRepository userRepository;
    private final PostService postService;
    private final PostRepository postRepository;
    private final ProductServiceItemRepository productServiceItemRepository;
    private final FileStorageService fileStorageService;
    private final NetworkService networkService;

    @GetMapping
    public String viewMyProfile(@AuthenticationPrincipal UserDetails userDetails, Model model) {
        if (userDetails == null) {
            return "redirect:/login";
        }
        User user = userRepository.findByUsername(userDetails.getUsername())
                .orElseThrow(() -> new RuntimeException("User not found"));
        model.addAttribute("user", user);
        model.addAttribute("currentUser", user);
        model.addAttribute("posts", postService.getPostsByAuthor(user));
        model.addAttribute("followersCount", networkService.getFollowers(user.getUsername()).size());
        model.addAttribute("followingCount", networkService.getFollowing(user.getUsername()).size());
        model.addAttribute("totalLikes", postRepository.countTotalLikesByAuthor(user));
        model.addAttribute("totalComments", postRepository.countTotalCommentsByAuthor(user));

        if (user.getRole() == Role.BUSINESS || user.getRole() == Role.CREATOR) {
            if (user.getBusinessProfile() == null) {
                BusinessProfile bp = new BusinessProfile();
                bp.setUser(user);
                user.setBusinessProfile(bp);
                // We don't necessarily need to save it here, just make it available for the
                // model
            }
            if (user.getBusinessProfile().getId() != null) {
                model.addAttribute("products",
                        productServiceItemRepository.findByBusinessProfile(user.getBusinessProfile()));
            } else {
                model.addAttribute("products", List.of());
            }
        }

        model.addAttribute("isOwner", true);
        return "profile";
    }

    @GetMapping("/profile/{username}")
    public String viewUserProfile(@PathVariable String username, @AuthenticationPrincipal UserDetails userDetails,
            Model model) {
        if (userDetails != null && userDetails.getUsername().equals(username)) {
            return "redirect:/users"; // Redirect to own profile if clicking own name
        }
        User targetUser = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));
        model.addAttribute("user", targetUser);
        model.addAttribute("followersCount", networkService.getFollowers(username).size());
        model.addAttribute("followingCount", networkService.getFollowing(username).size());

        User currentUser = null;
        if (userDetails != null) {
            currentUser = userRepository.findByUsername(userDetails.getUsername()).orElse(null);
            model.addAttribute("currentUser", currentUser);
        } else {
            model.addAttribute("currentUser", null);
        }

        boolean canView = true;
        if (targetUser.isPrivateProfile()) {
            canView = false;
            if (currentUser != null) {
                final Long currentUserId = currentUser.getId();
                boolean isFollower = networkService.getFollowers(targetUser.getUsername()).stream()
                        .anyMatch(u -> u.getId().equals(currentUserId));
                boolean isConnection = networkService.getConnections(targetUser.getUsername()).stream()
                        .anyMatch(u -> u.getId().equals(currentUserId));
                if (isFollower || isConnection) {
                    canView = true;
                }
            }
        }

        boolean isFollowing = false;
        if (currentUser != null) {
            isFollowing = networkService.getFollowing(currentUser.getUsername()).stream()
                    .anyMatch(u -> u.getId().equals(targetUser.getId()));
        }

        model.addAttribute("canView", canView);
        model.addAttribute("isFollowing", isFollowing);

        model.addAttribute("isConnected",
                networkService.areConnected(currentUser != null ? currentUser.getUsername() : null, username));
        model.addAttribute("isPending",
                networkService.isPending(currentUser != null ? currentUser.getUsername() : null, username));
        model.addAttribute("isIncomingPending",
                networkService.isPending(username, currentUser != null ? currentUser.getUsername() : null));

        if (canView) {
            model.addAttribute("posts", postService.getPostsByAuthor(targetUser));
            model.addAttribute("totalLikes", postRepository.countTotalLikesByAuthor(targetUser));
            model.addAttribute("totalComments", postRepository.countTotalCommentsByAuthor(targetUser));
            if (targetUser.getRole() == Role.BUSINESS || targetUser.getRole() == Role.CREATOR) {
                if (targetUser.getBusinessProfile() == null) {
                    BusinessProfile bp = new BusinessProfile();
                    bp.setUser(targetUser);
                    targetUser.setBusinessProfile(bp);
                }
                if (targetUser.getBusinessProfile().getId() != null) {
                    model.addAttribute("products",
                            productServiceItemRepository.findByBusinessProfile(targetUser.getBusinessProfile()));
                } else {
                    model.addAttribute("products", List.of());
                }
            }
        } else {
            model.addAttribute("posts", List.of());
        }

        model.addAttribute("isOwner", false);
        return "user-profile";
    }

    @GetMapping("/edit")
    public String editProfilePage(@AuthenticationPrincipal UserDetails userDetails, Model model) {
        User user = userRepository.findByUsername(userDetails.getUsername())
                .orElseThrow(() -> new RuntimeException("User not found"));

        if ((user.getRole() == Role.BUSINESS || user.getRole() == Role.CREATOR) && user.getBusinessProfile() == null) {
            BusinessProfile bp = new BusinessProfile();
            bp.setUser(user);
            user.setBusinessProfile(bp);
        }

        model.addAttribute("user", user);
        return "edit-profile";
    }

    @GetMapping("/{username}/followers")
    public String viewFollowers(@PathVariable String username, Model model) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));
        model.addAttribute("user", user);
        model.addAttribute("users", networkService.getFollowers(username));
        model.addAttribute("title", "Followers of " + username);
        return "user-list";
    }

    @GetMapping("/{username}/following")
    public String viewFollowing(@PathVariable String username, Model model) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));
        model.addAttribute("user", user);
        model.addAttribute("users", networkService.getFollowing(username));
        model.addAttribute("title", "Users followed by " + username);
        return "user-list";
    }

    @PostMapping("/edit")
    public String updateProfile(@AuthenticationPrincipal UserDetails userDetails, @ModelAttribute User updatedUser,
            @RequestParam(value = "profilePictureFile", required = false) MultipartFile profilePictureFile) {
        User currentUser = userRepository.findByUsername(userDetails.getUsername())
                .orElseThrow(() -> new RuntimeException("User not found"));

        if (profilePictureFile != null && !profilePictureFile.isEmpty()) {
            String fileName = fileStorageService.storeFile(profilePictureFile);
            currentUser.setProfilePictureUrl("/uploads/" + fileName);
        } else {
            currentUser.setProfilePictureUrl(updatedUser.getProfilePictureUrl());
        }
        currentUser.setBio(updatedUser.getBio());
        currentUser.setLocation(updatedUser.getLocation());
        currentUser.setWebsite(updatedUser.getWebsite());
        currentUser.setPrivateProfile(updatedUser.isPrivateProfile());
        currentUser.setPrefConnectionRequests(updatedUser.isPrefConnectionRequests());
        currentUser.setPrefLikes(updatedUser.isPrefLikes());
        currentUser.setPrefComments(updatedUser.isPrefComments());
        currentUser.setPrefFollows(updatedUser.isPrefFollows());
        currentUser.setPrefShares(updatedUser.isPrefShares());

        if (currentUser.getRole() == Role.BUSINESS || currentUser.getRole() == Role.CREATOR) {
            BusinessProfile bp = currentUser.getBusinessProfile();
            if (bp == null) {
                bp = new BusinessProfile();
                bp.setUser(currentUser);
                currentUser.setBusinessProfile(bp);
            }
            if (updatedUser.getBusinessProfile() != null) {
                bp.setBusinessName(updatedUser.getBusinessProfile().getBusinessName());
                bp.setCategory(updatedUser.getBusinessProfile().getCategory());
                bp.setAddress(updatedUser.getBusinessProfile().getAddress());
                bp.setBusinessHours(updatedUser.getBusinessProfile().getBusinessHours());
                bp.setContactLinks(updatedUser.getBusinessProfile().getContactLinks());
            }
        }

        userRepository.save(currentUser);
        return "redirect:/users";
    }

    @GetMapping("/search")
    public String searchUsers(@RequestParam(required = false) String query,
            @AuthenticationPrincipal UserDetails userDetails, Model model) {
        if (query != null && !query.isEmpty()) {
            if (query.startsWith("#")) {
                String hashtag = query.substring(1);
                model.addAttribute("posts", postService.searchByHashtag(hashtag));
                model.addAttribute("searchType", "Hashtag");
            } else {
                List<User> users = userRepository.findByUsernameContainingIgnoreCase(query);
                model.addAttribute("users", users);
                model.addAttribute("searchType", "Users");
            }
        }
        model.addAttribute("currentUser", userDetails);
        if (userDetails != null) {
            model.addAttribute("currentUsername", userDetails.getUsername());
            // Updated to use follow relationship instead of connections
            java.util.Set<String> followingUsernames = networkService.getFollowing(userDetails.getUsername()).stream()
                    .map(User::getUsername).collect(java.util.stream.Collectors.toSet());
            model.addAttribute("followingUsernames", followingUsernames);
        }
        return "search";
    }

    @PostMapping("/product/add")
    public String addProduct(@AuthenticationPrincipal UserDetails userDetails,
            @RequestParam String name,
            @RequestParam String description,
            @RequestParam String type,
            @RequestParam BigDecimal price,
            @RequestParam(value = "image", required = false) MultipartFile image) {
        User user = userRepository.findByUsername(userDetails.getUsername())
                .orElseThrow(() -> new RuntimeException("User not found"));

        if (user.getBusinessProfile() == null) {
            throw new RuntimeException("Business profile not found");
        }

        String imageUrl = null;
        if (image != null && !image.isEmpty()) {
            String fileName = fileStorageService.storeFile(image);
            imageUrl = "/uploads/" + fileName;
        }

        ProductServiceItem item = new ProductServiceItem(user.getBusinessProfile(), name, description, type, price,
                imageUrl);
        productServiceItemRepository.save(item);

        return "redirect:/users";
    }

    @PostMapping("/product/{id}/delete")
    public String deleteProduct(@PathVariable Long id, @AuthenticationPrincipal UserDetails userDetails) {
        User user = userRepository.findByUsername(userDetails.getUsername())
                .orElseThrow(() -> new RuntimeException("User not found"));

        ProductServiceItem item = productServiceItemRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Product not found"));

        if (!item.getBusinessProfile().getUser().getId().equals(user.getId())) {
            throw new RuntimeException("Unauthorized");
        }

        productServiceItemRepository.delete(item);
        return "redirect:/users";
    }

    public ProfileController(final UserRepository userRepository, final PostService postService,
            final PostRepository postRepository,
            final ProductServiceItemRepository productServiceItemRepository,
            final FileStorageService fileStorageService,
            final NetworkService networkService) {
        this.userRepository = userRepository;
        this.postService = postService;
        this.postRepository = postRepository;
        this.productServiceItemRepository = productServiceItemRepository;
        this.fileStorageService = fileStorageService;
        this.networkService = networkService;
    }
}
