// Generated by delombok at Tue Feb 24 10:16:30 IST 2026
package com.revconnect.app.controller;

import com.revconnect.app.service.SavedPostService;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestHeader;

@Controller
@RequestMapping("/saved")
public class SavedPostController {
    private final SavedPostService savedPostService;

    @PostMapping("/{postId}")
    public String toggleSavePost(@PathVariable Long postId, @AuthenticationPrincipal UserDetails userDetails, @RequestHeader(value = "Referer", defaultValue = "/") String referer) {
        savedPostService.toggleSavePost(userDetails.getUsername(), postId);
        return "redirect:" + referer; // Stay on the current page after saving
    }

    @GetMapping
    public String viewSavedPosts(Model model, @AuthenticationPrincipal UserDetails userDetails) {
        model.addAttribute("savedPosts", savedPostService.getSavedPosts(userDetails.getUsername()));
        return "saved-posts";
    }
    public SavedPostController(final SavedPostService savedPostService) {
        this.savedPostService = savedPostService;
    }
}
